### ISSUE TITLE
feat(gov): custom vote options

### ISSUE THREAD

**Issue by tbruyelle** [atomone-hub/govgen#3]
## Summary

We want to create a proposal with custom voting options, not just yes, no, NWV and abstain.

## Problem Definition

Yes/No proposals are too restrictive in terms of choices; having custom voting options would allow a single proposal to cover a whole set of options without the need to create multiple Yes/No proposals for each option (which can be a blocker considering the high deposit amount of govgen).

## Proposal

At the submit proposal step, it's possible to customize the vote options. Should only be possible for text proposals.

A similar feature has been recently shipped in the SDK, unfortunately in a version that is too recent, but we can maybe use it as a model: https://github.com/cosmos/cosmos-sdk/pull/18762

## Task list

- [ ] have a gov custom module (should be done once #2 is closed)
- [ ] Implement multiple choice proposals

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by tbruyelle** [comment]
Closed because having multiple choices introduces the Condorcet paradoxe. This can lead to abuse and manipulation of voters.
